# Generated by Django 4.1.7 on 2023-04-09 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_index', models.CharField(max_length=36, unique=True)),
                ('product_code', models.CharField(choices=[('hood-001', 'hood-001'), ('hood-002', 'hood-002'), ('hood-003', 'hood-003'), ('jean-001', 'jean-001'), ('socks-001', 'socks-001'), ('hat-001', 'hat-001')], max_length=10)),
                ('product_name', models.CharField(max_length=20)),
                ('product_size', models.CharField(choices=[('XS', 'X-Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X-Large'), ('F', 'Free')], max_length=2)),
                ('product_price', models.CharField(max_length=10)),
                ('product_desc', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'my_product',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product')),
                ('stock', models.IntegerField()),
                ('product_index', models.CharField(max_length=36, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'my_inventory',
            },
        ),
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_quantity', models.IntegerField(blank=True, default=0)),
                ('outbound_date', models.DateTimeField(auto_now_add=True)),
                ('product_index', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_products', to='products.product', to_field='product_index')),
            ],
            options={
                'db_table': 'my_outbound',
            },
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_quantity', models.IntegerField(blank=True, default=0)),
                ('inbound_date', models.DateTimeField(auto_now_add=True)),
                ('product_index', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_products', to='products.product', to_field='product_index')),
            ],
            options={
                'db_table': 'my_inbound',
            },
        ),
    ]
