# Generated by Django 4.2 on 2023-04-08 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10, unique=True)),
                ('product_name', models.CharField(max_length=15)),
                ('product_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('F', 'Free')], max_length=1)),
                ('product_price', models.CharField(max_length=10)),
                ('product_desc', models.TextField()),
            ],
            options={
                'db_table': 'my_product',
            },
        ),
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_quantity', models.IntegerField(blank=True, default=0)),
                ('outbound_date', models.DateTimeField(auto_now_add=True)),
                ('product_code', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_products', to='products.product', to_field='product_code')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(blank=True, default=0)),
                ('product_code', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_products', to='products.product', to_field='product_code')),
            ],
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_quantity', models.IntegerField(blank=True, default=0)),
                ('inbound_date', models.DateTimeField(auto_now_add=True)),
                ('product_code', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_products', to='products.product', to_field='product_code')),
            ],
        ),
    ]
