# Generated by Django 4.1.7 on 2023-04-07 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_inventory_product_code_alter_inventory_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbound',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_products', to='products.product'),
        ),
        migrations.AddField(
            model_name='outbound',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_products', to='products.product'),
        ),
    ]
