# Generated by Django 4.1.7 on 2023-04-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_inbound_product_outbound_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='inbound_quantity',
            field=models.IntegerField(blank=True, default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='outbound_quantity',
            field=models.IntegerField(blank=True, default=0, max_length=200),
        ),
    ]
