# Generated by Django 4.1.7 on 2023-04-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_inventory_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='inbound_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='outbound_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
