# Generated by Django 4.1.7 on 2023-04-08 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_inbound_inbound_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='product_code',
        ),
    ]
