# Generated by Django 4.2 on 2023-04-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='bio',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default='', max_length=15),
        ),
    ]
